---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: "install nginx on ubuntu"
      apt:
        name: nginx
        state: latest

    - name: "Make sure 'nginx' is started"
      service:
        name: nginx
        state: restarted
        enabled: yes

    - name: "get nxinx status"
      shell: "sudo systemctl status nginx"
      register: nginx_result

    - name: "File module, create directory"
      file:
        path: "/home/ubuntu/anj_test"
        owner: "ubuntu"
        group: "ubuntu"
        mode: 0755
        state: directory

    - file:
        path: "/home/ubuntu/anj_test/test1.txt"
        owner: "ubuntu"
        group: "ubuntu"
        mode: 0755
        state: touch

    - name: "Command Module"
      command: "ls -lrt"
      register: command_output

    - name: "print command results"
      debug:
        msg: "{{ command_output.stdout_lines }}"

